default: &default
  host: localhost
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  timeout: 5000

# development:
#   <<: *default
#   database: yalit_development
#   username: carsoncole
# password: password

development:
  <<: *default
  database: yallit-development
  username: carsoncole
  password: password

test:
  <<: *default
  database: yalit_test
  username: carsoncole
  password: password
