default: &default
  host: localhost
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  timeout: 5000

development:
  <<: *default
  database: yalit_development
  username: carsoncole
  password: password

# development:
#   <<: *default
#   host: ec2-174-129-253-104.compute-1.amazonaws.com
#   database: d7av4jjmluvot8
#   username: d7av4jjmluvot8
#   password: ab720eb4694563aba049cf4b9022549f280d96c0975bcea6d56f318110383788

test:
  <<: *default
  database: yalit_test
  username: carsoncole
  password: password
